version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "nuget"
    directory: "/src/Authentication/Authentication.Test"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    allow:
      - dependency-name: "Moq"