# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
trigger: none # disable triggers based on commits.
pr: none # disable as a PR gate.
name: 'Examples migration'
parameters:
- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 1200
- name: BuildAgent
  displayName: Build Agent
  default: 1es-windows-ps-compute

resources:
 repositories:     
  #  - repository: msgraph-sdk-powershell
  #    type: github
  #    endpoint: microsoftgraph
  #    name: microsoftgraph/msgraph-sdk-powershell
  #    ref: features/2.0
   - repository: DevRepo
     type: github
     endpoint: timayabi2020
     name: timayabi2020/msgraph-sdk-powershell
     ref: dev
  
jobs:
- job: PowerShellExamplesMigration
  pool: 
    name: ${{ parameters.BuildAgent }}
  timeoutInMinutes: ${{ parameters.PipelineTimeout }}
  steps:
  - checkout: self
  - checkout: DevRepo

  - task: PowerShell@2
    displayName: 'Migrate Examples From Dev Branch'
    continueOnError: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: tools\Migration\ExamplesMigration.ps1

  - task: PowerShell@2
    displayName: Pushing to github
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    inputs:
      targetType: inline
      pwsh: true
      script: |
        git config --global user.email "timwamalwa@gmail.com"
        git config --global user.name "Timothy Wamalwa"
        $date = Get-Date -Format "dd-MM-yyyy"
        $proposedBranch = "ExamplesMigration/"+$date
        git add .
        git commit -m "Migrating examples "+$date
        git push --set-upstream "https://$(GITHUB_TOKEN)@github.com/microsoftgraph/msgraph-sdk-powershell.git" $proposedBranch
        git status